export const KITS = [
  // ─── GAMME SOFAR POWERALL ─────────────────────────────────────────────────
  {
    id: "sofar-3kwc",
    gamme: "SOFAR PowerAll",
    nom: "Kit 3 kWc — SOFAR PowerAll",
    puissance_kwc: 2.93,
    nb_modules: 5,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "SOFAR",
    onduleur_modele: "ESI 3K-S1",
    onduleur_puissance_kw: 3,
    batterie_marque: "SOFAR",
    batterie_modele: "2x BTS 5K LFP",
    batterie_kwh: 9.98,
    structure_marque: "Novotegra",
    strings: "1 string de 5 (Voc 257V)",
    total_ht: 11517.70,
    tva: 8.5,
    total_ttc: 12496.70,
    tranche_s24: "3 kWc",
    prime_s24_eur_wc: 1.52,
    description: "Onduleur hybride + 2 batteries LFP 9,98 kWh utile. Solution la plus integree.",
    avantages: ["Onduleur hybride tout-en-un", "9,98 kWh de stockage", "Monitoring WiFi inclus", "Garantie 10 ans onduleur"],
    color: "#3b82f6",
  },
  {
    id: "sofar-6kwc",
    gamme: "SOFAR PowerAll",
    nom: "Kit 6 kWc — SOFAR PowerAll",
    puissance_kwc: 5.85,
    nb_modules: 10,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "SOFAR",
    onduleur_modele: "ESI 6K-S1",
    onduleur_puissance_kw: 6,
    batterie_marque: "SOFAR",
    batterie_modele: "2x BTS 5K LFP",
    batterie_kwh: 9.98,
    structure_marque: "Novotegra",
    strings: "2 strings de 5 (Voc 257V, 1/MPPT)",
    total_ht: 14570.80,
    tva: 8.5,
    total_ttc: 15809.32,
    tranche_s24: "9 kWc",
    prime_s24_eur_wc: 1.05,
    description: "2 rangees de 5 modules. Onduleur 6kW 2 MPPT. Ideal maison 4-5 personnes.",
    avantages: ["PV max 9000 Wc", "2 MPPT independants", "9,98 kWh de stockage", "Extensible +1 batterie"],
    color: "#3b82f6",
  },
  {
    id: "sofar-9kwc",
    gamme: "SOFAR PowerAll",
    nom: "Kit 9 kWc — SOFAR PowerAll",
    puissance_kwc: 8.78,
    nb_modules: 15,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "SOFAR",
    onduleur_modele: "ESI 6K-S1",
    onduleur_puissance_kw: 6,
    batterie_marque: "SOFAR",
    batterie_modele: "3x BTS 5K LFP",
    batterie_kwh: 14.98,
    structure_marque: "Novotegra",
    strings: "Strings 8+7 (Voc max 411V)",
    total_ht: 20807.20,
    tva: 8.5,
    total_ttc: 22575.81,
    tranche_s24: "9 kWc",
    prime_s24_eur_wc: 1.05,
    description: "3 rangees. 14,98 kWh de stockage. Solution maximale en hybride SOFAR.",
    avantages: ["14,98 kWh de stockage", "Strings 8+7 optimises", "Solution complete famille", "Autonomie maximale"],
    color: "#3b82f6",
  },

  // ─── GAMME ALPHA ESS SMILE ────────────────────────────────────────────────
  {
    id: "smile-3kwc",
    gamme: "Alpha ESS SMILE",
    nom: "Kit 3 kWc — Alpha ESS SMILE-B3-PLUS",
    puissance_kwc: 2.93,
    nb_modules: 5,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "Alpha ESS + SOFAR",
    onduleur_modele: "SMILE-B3-PLUS + 3KTLM-G3",
    onduleur_puissance_kw: 3,
    batterie_marque: "Alpha ESS",
    batterie_modele: "SMILE-B3-PLUS LFP",
    batterie_kwh: 4.79,
    structure_marque: "Novotegra",
    strings: "1 string de 5",
    total_ht: 8070.20,
    tva: 8.5,
    total_ttc: 8756.17,
    tranche_s24: "3 kWc",
    prime_s24_eur_wc: 1.52,
    description: "Couplage AC. Stockage 4,79 kWh. Solution economique extensible jusqu'a 30 kWh.",
    avantages: ["Prix d'entree attractif", "Extensible jusqu'a 30 kWh", "Compatible tous onduleurs", "Batterie tout-en-un"],
    color: "#10b981",
  },
  {
    id: "smile-6kwc",
    gamme: "Alpha ESS SMILE",
    nom: "Kit 6 kWc — Alpha ESS SMILE5",
    puissance_kwc: 5.85,
    nb_modules: 10,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "Alpha ESS",
    onduleur_modele: "SMILE5 hybride",
    onduleur_puissance_kw: 5,
    batterie_marque: "Alpha ESS",
    batterie_modele: "SMILE5-BAT 5,7 kWh",
    batterie_kwh: 5.5,
    structure_marque: "Novotegra",
    strings: "2 strings de 5",
    total_ht: 12603.30,
    tva: 8.5,
    total_ttc: 13674.58,
    tranche_s24: "9 kWc",
    prime_s24_eur_wc: 1.05,
    description: "Onduleur hybride SMILE5 5kW. Economique vs SOFAR. Option 2 batteries disponible.",
    avantages: ["1968 euros de moins que SOFAR", "UPS integre", "PV max 7500 Wc", "Extension facile"],
    color: "#10b981",
  },
  {
    id: "smile-9kwc",
    gamme: "Alpha ESS SMILE",
    nom: "Kit 9 kWc — Alpha ESS couplage AC",
    puissance_kwc: 8.78,
    nb_modules: 15,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "SOFAR + Alpha ESS",
    onduleur_modele: "6KTLM-G3 + SMILE-B3-PLUS",
    onduleur_puissance_kw: 6,
    batterie_marque: "Alpha ESS",
    batterie_modele: "SMILE-B3-PLUS + BAT-5P",
    batterie_kwh: 9.58,
    structure_marque: "Novotegra",
    strings: "Strings 8+7",
    total_ht: 16749.70,
    tva: 8.5,
    total_ttc: 18173.42,
    tranche_s24: "9 kWc",
    prime_s24_eur_wc: 1.05,
    description: "Architecture couplage AC. SOFAR 6KTLM + SMILE-B3-PLUS. 9,58 kWh utile.",
    avantages: ["4058 euros de moins que SOFAR hybride", "9,58 kWh stockage", "Architecture souple", "Compatible toiture complexe"],
    color: "#10b981",
  },

  // ─── GAMME MICRO-ONDULEURS HOYMILES ───────────────────────────────────────
  {
    id: "micro-3kwc",
    gamme: "Micro-onduleurs Hoymiles",
    nom: "Kit 3 kWc — Hoymiles + SMILE-B3-PLUS",
    puissance_kwc: 2.93,
    nb_modules: 5,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "Hoymiles",
    onduleur_modele: "5x HMS-500-1T",
    onduleur_puissance_kw: 2.5,
    batterie_marque: "Alpha ESS",
    batterie_modele: "SMILE-B3-PLUS LFP",
    batterie_kwh: 4.79,
    structure_marque: "Novotegra",
    strings: "1 micro par module (tout AC)",
    total_ht: 7522.70,
    tva: 8.5,
    total_ttc: 8162.13,
    tranche_s24: "3 kWc",
    prime_s24_eur_wc: 1.52,
    description: "1 micro-onduleur par module. Pas de courant continu sur la toiture. Ideal ombrage.",
    avantages: ["Optimisation module par module", "Zero DC sur toiture", "Securite incendie maximale", "Monitoring par module"],
    color: "#f59e0b",
  },
  {
    id: "micro-6kwc",
    gamme: "Micro-onduleurs Hoymiles",
    nom: "Kit 6 kWc — Hoymiles + SMILE-B3-PLUS",
    puissance_kwc: 5.85,
    nb_modules: 10,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "Hoymiles",
    onduleur_modele: "10x HMS-500-1T",
    onduleur_puissance_kw: 5,
    batterie_marque: "Alpha ESS",
    batterie_modele: "SMILE-B3-PLUS + BAT-5P",
    batterie_kwh: 9.58,
    structure_marque: "Novotegra",
    strings: "1 micro par module (tout AC)",
    total_ht: 14570.30,
    tva: 8.5,
    total_ttc: 15808.78,
    tranche_s24: "9 kWc",
    prime_s24_eur_wc: 1.05,
    description: "10 micros independants. 9,58 kWh stockage. Ideal toiture a orientations mixtes.",
    avantages: ["Parfait pour ombrage partiel", "9,58 kWh stockage", "Monitoring DTU-Pro-S inclus", "Extensible en modules"],
    color: "#f59e0b",
  },
  {
    id: "micro-9kwc",
    gamme: "Micro-onduleurs Hoymiles",
    nom: "Kit 9 kWc — Hoymiles + SMILE-B3-PLUS",
    puissance_kwc: 8.78,
    nb_modules: 15,
    panneau_marque: "Polycrown",
    panneau_modele: "NS-585MH-144",
    panneau_wc: 585,
    onduleur_marque: "Hoymiles",
    onduleur_modele: "15x HMS-500-1T",
    onduleur_puissance_kw: 7.5,
    batterie_marque: "Alpha ESS",
    batterie_modele: "SMILE-B3-PLUS + BAT-5P",
    batterie_kwh: 9.58,
    structure_marque: "Novotegra",
    strings: "1 micro par module (tout AC)",
    total_ht: 16915.70,
    tva: 8.5,
    total_ttc: 18353.53,
    tranche_s24: "9 kWc",
    prime_s24_eur_wc: 1.05,
    description: "15 micros. Aucune limite d'entree PV. Solution ideale grandes toitures complexes.",
    avantages: ["Aucune limite PV centrale", "Ideal grandes toitures", "9,58 kWh stockage", "Architecture 100% AC"],
    color: "#f59e0b",
  },
];

export const GAMMES = ["SOFAR PowerAll", "Alpha ESS SMILE", "Micro-onduleurs Hoymiles"];

export function getKitById(id) {
  return KITS.find(k => k.id === id) || null;
}

export function getKitsByGamme(gamme) {
  return KITS.filter(k => k.gamme === gamme);
}

export function calculerPrimeS24(kit) {
  const puissance_wc = kit.puissance_kwc * 1000;
  return +(puissance_wc * kit.prime_s24_eur_wc).toFixed(2);
}